version: 2
updates:
  # github actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"

  # rust dependencies
  - package-ecosystem: "cargo"
    directory: "/rust"
    schedule:
      interval: "weekly"

  # npm/js dependencies
  - package-ecosystem: "npm"
    directory: "/js"
    schedule:
      interval: "weekly"
