name: Rust

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    
    steps:
      - uses: actions/checkout@v7
      
      - name: Update Rust toolchain
        run: rustup update stable && rustup default stable
        
      - name: Build
        working-directory: ./rust
        run: cargo build --verbose
        
      - name: Run tests
        working-directory: ./rust
        run: cargo test --verbose
